name: Asana

on: [pull_request]

jobs:
  asana-sync:
    runs-on: ubuntu-latest
    name: Asana Sync
    steps:
      - uses: insurify/github-asana-action@v1.0.1
        with:
          asana-pat: "1/496430239795212:21b139860eb3df3cf957ba74f0b8f1d6"
          task-comment: "PR => "
          trigger-phrase: "Asana Task:"
